from __future__ import annotations

import argparse
from dataclasses import replace

from .ui import WizardApp
from .config import default_config, get_lastfm_api_key, get_lastfm_session, get_lastfm_shared_secret
from .paths import AUDIO_EXTENSIONS, COVER_EXTENSIONS, resolve_media_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="wizard-cli")
    parser.add_argument("--songs-dir", default=None, help="override beats dir")
    parser.add_argument("--covers-dir", default=None, help="override covers dir")
    subparsers = parser.add_subparsers(dest="command")

    ui_parser = subparsers.add_parser("ui", help="run pipeline in ui mode")
    ui_parser.set_defaults(command="ui")

    run_parser = subparsers.add_parser("run", help="run pipeline in headless mode")
    run_parser.add_argument("--beat", required=True)
    run_parser.add_argument("--cover", required=True)
    run_parser.add_argument("--artists", required=True, help="comma-separated list of artists")
    run_parser.add_argument(
        "--descriptors",
        default="",
        help="comma-separated genres, styles, structures, or other guaranteed modifiers",
    )
    run_parser.add_argument("--title", default="wizard-cli upload")
    run_parser.add_argument("--body", default="Generated by wizard-cli")
    run_parser.add_argument("--lastfm-api-key", default=None)
    run_parser.add_argument("--publish", action="store_true")
    run_parser.set_defaults(command="run")
    setup_parser = subparsers.add_parser("setup", help="auto-install dependencies")
    setup_parser.add_argument("--auto-mpv", action="store_true", help="attempt to auto-download and install mpv to user folder")
    setup_parser.add_argument("--mpv-url", default=None, help="direct URL to an mpv zip build to download when using --auto-mpv")
    setup_parser.set_defaults(command="setup")
    auth_parser = subparsers.add_parser("auth", help="run Last.fm desktop auth flow and store session key")
    auth_parser.add_argument("--api-key", default=None, help="Last.fm API key (falls back to stored key)")
    auth_parser.add_argument("--shared-secret", default=None, help="Last.fm shared secret (or set WIZARDCLI_LASTFM_SECRET env var)")
    auth_parser.set_defaults(command="auth")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = default_config(songs_dir=args.songs_dir, covers_dir=args.covers_dir)

    if args.command in (None, "ui"):
        WizardApp(config).run()
        return 0

    if args.command == "run":
        from .pipeline import run_pipeline

        beat = resolve_media_path(config.songs_dir, args.beat, allowed_extensions=AUDIO_EXTENSIONS)
        cover = resolve_media_path(config.covers_dir, args.cover, allowed_extensions=COVER_EXTENSIONS)
        artist_names = [item.strip() for item in args.artists.split(",") if item.strip()]
        descriptors = [item.strip() for item in args.descriptors.split(",") if item.strip()]
        config = replace(config, publish_enabled=bool(args.publish))
        lastfm_key = args.lastfm_api_key or get_lastfm_api_key()
        lastfm_session = get_lastfm_session()
        run_pipeline(
            config,
            beat=beat,
            cover=cover,
            artist_names=artist_names,
            descriptors=descriptors,
            title=args.title,
            body=args.body,
            lastfm_api_key=lastfm_key,
            lastfm_session_key=lastfm_session,
        )
        return 0

    if args.command == "setup":
        from .setup import run_setup

        result = run_setup(auto_mpv=bool(getattr(args, "auto_mpv", False)), mpv_url=getattr(args, "mpv_url", None))
        print(f"python audio deps installed: {result.python_installed}")
        print(f"mpv installed: {result.mpv_installed} path={result.mpv_path}")
        return 0

    if args.command == "auth":
        # run desktop auth flow
        from .lastfm_auth import do_desktop_auth
        from .config import set_lastfm_session

        api_key = args.api_key or get_lastfm_api_key()
        if not api_key:
            print("No API key found in ~/.wizardcli/wizardcli.json")
            return 2
        secret = args.shared_secret or get_lastfm_shared_secret()
        if not secret:
            print("No shared secret found in ~/.wizardcli/wizardcli.json")
            return 2
        resp = do_desktop_auth(api_key, secret)
        if not resp:
            print("Authentication failed")
            return 1
        session = resp.get("session", {})
        key = session.get("key")
        name = session.get("name")
        if key:
            set_lastfm_session(key, username=name)
            print(f"Stored session key for user: {name}")
            return 0
        print("Did not find session key in response")
        return 1

    parser.error(f"Unknown command: {args.command}")
    return 2
