from __future__ import annotations

import argparse
from dataclasses import replace

from .app import WizardApp
from .config import default_config
from .paths import AUDIO_EXTENSIONS, COVER_EXTENSIONS, resolve_media_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="wizard-cli")
    parser.add_argument("--songs-dir", default=None, help="Override the beats folder")
    parser.add_argument("--covers-dir", default=None, help="Override the covers folder")
    subparsers = parser.add_subparsers(dest="command")

    ui_parser = subparsers.add_parser("ui", help="Launch the Textual dashboard")
    ui_parser.set_defaults(command="ui")

    run_parser = subparsers.add_parser("run", help="Run the headless pipeline")
    run_parser.add_argument("--beat", required=True)
    run_parser.add_argument("--cover", required=True)
    run_parser.add_argument("--artists", required=True, help="Comma-separated artist names")
    run_parser.add_argument("--title", default="wizard-cli upload")
    run_parser.add_argument("--body", default="Generated by wizard-cli")
    run_parser.add_argument("--lastfm-api-key", default=None)
    run_parser.add_argument("--publish", action="store_true")
    run_parser.set_defaults(command="run")
    setup_parser = subparsers.add_parser("setup", help="Install optional deps and optionally download mpv")
    setup_parser.add_argument("--auto-mpv", action="store_true", help="Attempt to auto-download and install mpv to user folder")
    setup_parser.add_argument("--mpv-url", default=None, help="Direct URL to an mpv zip build to download when using --auto-mpv")
    setup_parser.set_defaults(command="setup")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = default_config(songs_dir=args.songs_dir, covers_dir=args.covers_dir)

    if args.command in (None, "ui"):
        WizardApp(config).run()
        return 0

    if args.command == "run":
        from .pipeline import run_pipeline

        beat = resolve_media_path(config.songs_dir, args.beat, allowed_extensions=AUDIO_EXTENSIONS)
        cover = resolve_media_path(config.covers_dir, args.cover, allowed_extensions=COVER_EXTENSIONS)
        artist_names = [item.strip() for item in args.artists.split(",") if item.strip()]
        config = replace(config, publish_enabled=bool(args.publish))
        run_pipeline(
            config,
            beat=beat,
            cover=cover,
            artist_names=artist_names,
            title=args.title,
            body=args.body,
            lastfm_api_key=args.lastfm_api_key,
        )
        return 0

    if args.command == "setup":
        from .setup import run_setup

        result = run_setup(auto_mpv=bool(getattr(args, "auto_mpv", False)), mpv_url=getattr(args, "mpv_url", None))
        print(f"python audio deps installed: {result.python_installed}")
        print(f"mpv installed: {result.mpv_installed} path={result.mpv_path}")
        return 0

    parser.error(f"Unknown command: {args.command}")
    return 2
